### ISSUE TITLE
Avoid Allocating when Reading a `&[u16]`

### ISSUE THREAD

**Issue by HTG-YT** [HTG-YT/IronJVM#1]
Currently, the implementation of `read_u2_many`:

https://github.com/HTG-YT/IronJVM/blob/9f0092f34eb3b2590f117d0a8712f37d5fd0fec2/ironjvm/ironjvm_cfparser/src/lib.rs#L126-L131

Allocates "unnecessary" memory on the heap through the use of a `Vec`.

A solution should be developed such that the allocation can be removed by directly casting a `&[u8]` into a `&[u16]` while taking into account that all Java class-files are read in BE.

**Comment by HTG-YT** [comment]
> > that all Java integers are BE.
> 
> That's not the reason.
> 
> Correction -> that the **class file format** is in Big-Endian.

Issue description updated.

**Comment by HTG-YT** [comment]
The allocation can not be avoided after consolidation, and is only avoided when the target endianness is BE.

**Comment by gimbles** [comment]
> The allocation can not be avoided after consolidation, and is only avoided when the target endianness is BE.

This is not true, you can have Big-Endian types on Little-Endian target systems by using endian-aware types provided by the `rend` crate
